### ISSUE TITLE
Hair segmentation doesn't work properly compared to Android implementation

### ISSUE THREAD

**Issue by stepanov-standy** [doreai/IOSFrameworks#1]
Hello, I am using your paid version and see huge difference between iOS and Android hair segmentation quality. Please let me know your support email do discuss details and find a solution.

**Comment by doreai** [comment]
Hi,  
Thanks for reaching out.
Please contact support@visionlab.co.in or doreai@visionlab.co.in with more details.
Note : Android SDK performance will be vary based mobile hardware configuration
